language: node_js
cache: yarn
node_js:
- '11'
script:
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
    repo: ryb73/opt-ex
  api_key:
    secure: sKdvx5nTQd4C2RxFfPxkTsGKAocQIW5PTmgQvPhG/9IBQOlPc9qTI7fw4jtgvy7PHSuVaalxuN4ymC3IuJeKgno3/XRcprQcfbH/x0QlqOxVpJEtiC4/UpGkSnyg06vFuDIy4fArbrRXewyvaO/QkAree411Q0tAanTKKhGQB+1WtcQSVS++zWW1/n+WUF4dNYQjGvPLtcgn/zH8GfyZaag1DzeHKs6PtYEFf1HF6YexZGyrFeNcr5AB5kbyYeNPl9inC0zOddJMdJpYcgpnER3EDywyYA3uf0EX1df4pmPT86Okg2stvOUjvKhSbBPPOLhu7ynuJ1dSrumLulAvtknZpVXLsElMcHccktO6aLno/MSnb+DZ/PZqCgcqO67l4RzzpsyNeMJd3rOTAvCio1+HYWXET0G8PiOCSpiJRgGVoU/uktqT9DDd1yk8bMKOCHF9enJGnDCexEhv/yg44S4xdBI/LW6KZ5EvCTgp6eZUyBBJCld86R4BxT5oBw2nOUhchMiT7aapyUn91ihqOkitio/D8gveAabAkPoruoeMdakBGEaR0LSMLszqpep3Ysy/yzvsRet0AsnNuBUSNYV3bO8PF1xhZZjg35FMmoEJ3B469nqAlaQQs5LQiiZMsdCf6x1DJgIGhn9g/5JpZIj+gHQQq85s1KOt2t4PApE=
