nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# https://github.com/yarnpkg/berry/issues/719#issuecomment-727088463
yarnPath: .yarn/releases/yarn-sources.cjs
